// RN bridge to the Pears match-room worklet. The worklet runs the same
// room-core the laptop peer runs; this file only starts the Bare worklet and
// speaks the newline-JSON IPC protocol. The bundle is generated by
// `npm run bundle:room` (bare-pack) — regenerate after editing worklet/*.js.
import { Worklet } from "react-native-bare-kit";
import { cfg } from "../config";

// bare-pack --format bundle.cjs emits `module.exports = "<bundle>"`, which
// Metro loads as a plain string module.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const bundle: string = require("./room.bundle.js");

export type RoomEvent =
  | { ev: "worklet-ready" }
  | { ev: "joining"; topic: string }
  | { ev: "ready"; me: string; name: string; lang: string }
  | { ev: "announced" }
  | { ev: "flushed"; peers: number }
  | { ev: "peer"; key: string; name: string; lang: string; peers: number }
  | { ev: "peer-gone"; key: string; name: string | null; peers: number }
  | { ev: "msg"; key: string; name: string; lang: string; text: string; ts: number; id: string }
  | { ev: "sent"; id: string; ts: number; lang: string; text: string; name: string; self: true }
  | { ev: "left" }
  | { ev: "err"; msg: string };

export type Room = { send: (text: string) => void; leave: () => void };

export function joinRoom(
  opts: { name: string; lang: string; topic?: string },
  onEvent: (e: RoomEvent) => void,
): Room {
  const worklet = new Worklet();
  worklet.start("/room.bundle", bundle);

  const enc = new TextEncoder();
  const dec = new TextDecoder();
  let pending = "";
  worklet.IPC.on("data", (chunk) => {
    pending += dec.decode(chunk as Uint8Array, { stream: true });
    let i: number;
    while ((i = pending.indexOf("\n")) !== -1) {
      const line = pending.slice(0, i);
      pending = pending.slice(i + 1);
      if (!line.trim()) continue;
      try { onEvent(JSON.parse(line) as RoomEvent); } catch { /* skip malformed line */ }
    }
  });

  const write = (obj: unknown) => worklet.IPC.write(enc.encode(JSON.stringify(obj) + "\n"));
  write({
    op: "join", topic: opts.topic ?? cfg.room.topic, name: opts.name, lang: opts.lang,
    maxMessageBytes: cfg.room.maxMessageBytes, bootstrap: cfg.room.bootstrap,
  });

  return {
    send: (text: string) => write({ op: "send", text }),
    leave: () => {
      try { write({ op: "leave" }); } catch { /* worklet already down */ }
      // Give the worklet a beat to destroy the swarm before tearing it down.
      setTimeout(() => { try { worklet.terminate(); } catch { /* already terminated */ } }, 300);
    },
  };
}
